# For: Web frontend repos (React/SPA/etc.)
name: DAST - Web App Baseline

on:
  schedule:
    - cron: '0 3 * * 1'  # Weekly Monday 3 AM UTC
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Web app URL to scan'
        required: true
        default: 'https://staging.yourapp.com'
      context_file:
        description: 'Optional ZAP context file (for auth)'
        required: false
      context_url:
        description: 'Optional context URL (for auth)'
        required: false
      user:
        description: 'Optional ZAP user (for auth)'
        required: false
      rules_file_name:
        description: 'Optional ZAP rules file path (e.g., .zap/rules.tsv)'
        required: false
      cmd_options:
        description: 'Optional ZAP cmd options'
        required: false
      data_classification:
        description: 'ISO 27701 data classification (e.g., None, PII)'
        required: false
      privacy_impact:
        description: 'ISO 27701 privacy impact summary'
        required: false

env:
  DEFAULT_TARGET_URL: https://staging.yourapp.com

jobs:
  dast-baseline:
    name: DAST - Web Baseline
    uses: your-org/.github/.github/workflows/reusable-zap-baseline.yml@main
    with:
      target_url: ${{ github.event.inputs.target_url || env.DEFAULT_TARGET_URL }}
      scan_type: 'baseline'
      context_file: ${{ github.event.inputs.context_file }}
      context_url: ${{ github.event.inputs.context_url }}
      user: ${{ github.event.inputs.user }}
      rules_file_name: ${{ github.event.inputs.rules_file_name }}
      cmd_options: ${{ github.event.inputs.cmd_options }}
      data_classification: ${{ github.event.inputs.data_classification }}
      privacy_impact: ${{ github.event.inputs.privacy_impact }}
