# For: backend-api repo
name: DAST Scans

on:
  workflow_call:
    inputs: 
      target_url:
        description: 'API URL to scan'
        required: true
        type: string
        default: 'https://staging-api.yourapp.com'
      openapi_url:
        description: 'OpenAPI spec URL'
        required: true
        type: string
        default: 'https://staging-api.yourapp.com/api-docs/swagger.json'
      context_file:
        description: 'Optional ZAP context file (for auth)'
        required: false
        type: string
      context_url:
        description: 'Optional context URL (for auth)'
        required: false
        type: string
      user:
        description: 'Optional ZAP user (for auth)'
        required: false
        type: string
      rules_file_name:
        description: 'Optional ZAP rules file path (e.g., .zap/rules.tsv)'
        required: false
        type: string
      cmd_options:
        description: 'Optional ZAP cmd options'
        required: false
        type: string
      data_classification:
        description: 'ISO 27701 data classification (e.g., None, PII)'
        required: false
        type: string
      privacy_impact:
        description: 'ISO 27701 privacy impact summary'
        required: false
        type: string

env:
  DEFAULT_TARGET_URL: https://staging-api.yourapp.com
  DEFAULT_OPENAPI_URL: https://staging-api.yourapp.com/api-docs/swagger.json

jobs:
  dast-api:
    name: DAST - API Scan
    uses: your-org/.github/.github/workflows/reusable-zap-baseline.yml@main
    with:
      target_url: ${{ inputs.target_url || env.DEFAULT_TARGET_URL }}
      scan_type: 'api'
      openapi_url: ${{ inputs.openapi_url || env.DEFAULT_OPENAPI_URL }}
      context_file: ${{ inputs.context_file }}
      context_url: ${{ inputs.context_url }}
      user: ${{ inputs.user }}
      rules_file_name: ${{ inputs.rules_file_name }}
      cmd_options: ${{ inputs.cmd_options }}
      data_classification: ${{ inputs.data_classification }}
      privacy_impact: ${{ inputs.privacy_impact }}
  
  dast-baseline:
    name: DAST - Baseline Scan
    uses: your-org/.github/.github/workflows/reusable-zap-baseline.yml@main
    with:
      target_url: ${{ inputs.target_url || env.DEFAULT_TARGET_URL }}
      scan_type: 'baseline'
      context_file: ${{ inputs.context_file }}
      context_url: ${{ inputs.context_url }}
      user: ${{ inputs.user }}
      rules_file_name: ${{ inputs.rules_file_name }}
      cmd_options: ${{ inputs.cmd_options }}
      data_classification: ${{ inputs.data_classification }}
      privacy_impact: ${{ inputs.privacy_impact }}