# For: backend-api repo
name: DAST Scans

on:
  schedule:
    - cron: '0 3 * * 1'  # Weekly Monday 3 AM UTC
  workflow_dispatch:
    inputs: 
      target_url:
        description: 'API URL to scan'
        required: true
        default: 'https://staging-api.yourapp.com'

jobs:
  dast-api:
    name: DAST - API Scan
    uses: your-org/.github/.github/workflows/reusable-zap-baseline.yml@main
    with:
      target_url: ${{ github.event.inputs.target_url || 'https://staging-api.yourapp.com' }}
      scan_type: 'api'
      openapi_url: 'https://staging-api.yourapp.com/api-docs/swagger.json'
  
  dast-baseline:
    name: DAST - Baseline Scan
    uses: your-org/.github/.github/workflows/reusable-zap-baseline.yml@main
    with:
      target_url: ${{ github.event.inputs.target_url || 'https://staging-api.yourapp.com' }}
      scan_type: 'baseline'