name: Reusable Semgrep SAST

on:
  workflow_call:
    inputs: 
      additional_configs:
        description: 'Additional Semgrep rule configs'
        required: false
        type: string
        default: ''

jobs:
  semgrep: 
    name:  SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep
        run: |
          semgrep scan \
            --config auto \
            --config p/security-audit \
            --config p/secrets \
            --config p/owasp-top-ten \
            ${{ inputs.additional_configs }} \
            --sarif --output semgrep. sarif \
            --json --output semgrep.json
        continue-on-error: true
      
      - name: Generate Summary
        if: always()
        run: |
          echo "## 🔒 SAST Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tool:** Semgrep" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f semgrep.json ]; then
            TOTAL=$(cat semgrep.json | jq '.results | length')
            HIGH=$(cat semgrep.json | jq '[.results[] | select(.extra.severity == "ERROR")] | length')
            MEDIUM=$(cat semgrep.json | jq '[.results[] | select(.extra.severity == "WARNING")] | length')
            echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
            echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
            echo "| High | $HIGH |" >> $GITHUB_STEP_SUMMARY
            echo "| Medium | $MEDIUM |" >> $GITHUB_STEP_SUMMARY
            echo "| Total | $TOTAL |" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
        continue-on-error: true
      
      - name: Upload artifacts (audit evidence)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sast-report-${{ github.sha }}
          path: |
            semgrep.sarif
            semgrep.json
          retention-days: 90  # ISO audit evidence retention