name: Security Pipeline

on:
  workflow_call:
    inputs:
      target_url:
        description: 'Target URL for DAST (staging)'
        required: false
        type: string
        default: 'https://staging.yourapp.com'
      run_dast:
        description: 'Whether to run DAST'
        required: false
        type: boolean
        default: true

env:
  DEFAULT_TARGET_URL: https://staging.yourapp.com

jobs:
  # SAST runs on every PR/push
  sast:
    name: SAST - Semgrep
    uses: ./.github/workflows/reusable-semgrep.yml
    with:
      data_classification: 'PII (app-dependent)'
      privacy_impact: 'Review repo data handling'

  # DAST runs only on main branch (after deployment)
  dast:
    name: DAST - OWASP ZAP
    needs: sast  # Run after SAST
    if: inputs.run_dast
    uses: ./.github/workflows/reusable-zap-baseline.yml
    with:
      target_url: ${{ inputs.target_url || env.DEFAULT_TARGET_URL }}
      scan_type: 'baseline'
      data_classification: 'PII (app-dependent)'
      privacy_impact: 'Review web data handling'

  # Summary job
  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [sast, dast]
    if: always()
    steps:
      - name: Generate Summary
        run: |
          echo "## 🔒 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### SAST (Semgrep)" >> $GITHUB_STEP_SUMMARY
          echo "- See job summary and artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### DAST (OWASP ZAP)" >> $GITHUB_STEP_SUMMARY
          echo "- See job summary and artifacts" >> $GITHUB_STEP_SUMMARY