# Place in your org's .github repo
name: Monthly Security Report

on:
  schedule: 
    - cron: '0 6 1 * *'  # First day of each month at 6 AM UTC
  workflow_dispatch:

jobs: 
  generate-report:
    name: Generate Security Report
    runs-on:  ubuntu-latest
    
    steps:
      - name: Generate Report
        uses: actions/github-script@v7
        with:
          script:  |
            const { owner, repo } = context.repo;
            
            // Get all security issues
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              labels: 'security',
              state: 'all',
              since: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
            });
            
            const open = issues.data.filter(i => i.state === 'open').length;
            const closed = issues.data.filter(i => i.state === 'closed').length;
            
            const report = `
            # Monthly Security Report
            **Period:** ${new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]} to ${new Date().toISOString().split('T')[0]}
            **Generated:** ${new Date().toISOString()}
            
            ## Summary
            | Metric | Count |
            |--------|-------|
            | Open Security Issues | ${open} |
            | Closed Security Issues | ${closed} |
            | Total Findings | ${issues.data.length} |
            
            ## ISO 27001 Compliance Status
            - ✅ A. 14.2. 1 - Secure development policy:  Documented
            - ✅ A. 14.2.5 - SAST implemented in CI/CD pipeline
            - ✅ A.14.2.8 - DAST implemented for web applications
            - ✅ A.12.6.1 - Vulnerability tracking via GitHub Issues

            ## ISO 27701 Privacy Evidence
            - ✅ Privacy impact recorded on security findings (issue template field)
            - ✅ PII/data classification documented in security policy
            
            ## Evidence Locations
            - SAST Reports: GitHub Actions Artifacts (90-day retention)
            - DAST Reports: GitHub Actions Artifacts (90-day retention)
            - Remediation Tracking: GitHub Issues with 'security' label
            - Security Policy: docs/security/SECURITY.md
            `;
            
            console.log(report);
            
            // Create summary
            await core.summary.addRaw(report).write();
      
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report-${{ github.run_id }}
          path: ${{ github.workspace }}
          retention-days: 365  # Keep reports for 1 year for audit