name: Semgrep SAST (Optimized)

on:
  workflow_call:
    inputs:
      scan_mode:
        description: 'diff or full'
        required: false
        type: string
        default: 'full'
      baseline_commit:
        description: 'Baseline commit for diff scan'
        required: false
        type: string

concurrency:
  group: semgrep-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    name:  Semgrep Scan
    runs-on: ubuntu-latest  # 1x multiplier
    if: github.repository == 'your-org/your-repo'
    
    container:
      image: semgrep/semgrep
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth:  0  # Full history for better diff scanning
      
      # Only scan changed files on PRs (faster!)
      - name: Scan changed files only
        if: inputs.scan_mode == 'diff' && inputs.baseline_commit != ''
        run: |
          semgrep scan --config auto --config p/security-audit \
            --json --output results.json \
            --baseline-commit ${{ inputs.baseline_commit }}
      
      # Full scan on push to main
      - name: Full scan
        if: inputs.scan_mode == 'full'
        run: |
          semgrep scan --config auto --config p/security-audit \
            --json --output results.json
      
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: results.json