name: OWASP ZAP Full Scan

on:
  workflow_call:
    inputs: 
      target_url:
        description: 'Target URL to scan'
        required: true
        type: string
        default: 'https://staging.yourapp.com'
      allow_issue_writing:
        description: 'Allow creating GitHub issues for findings'
        required: false
        type: boolean
        default: true
      cmd_options:
        description: 'Optional ZAP command options'
        required: false
        type: string
        default: '-T 60'

jobs:
  zap-full:
    name: ZAP Full Scan
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: ${{ inputs.target_url || 'https://staging.yourapp.com' }}
          fail_action: false
          allow_issue_writing: ${{ inputs.allow_issue_writing }}
          artifact_name: zap-full-report
          # Limit scan time to control minutes usage
          cmd_options: ${{ inputs.cmd_options }}  # Max 60 minutes

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-full-report
          path: report_html.html
          retention-days: 90