name: OWASP ZAP Baseline Scan

on:
  # Run weekly
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 3 AM UTC
  # Or trigger manually
  workflow_dispatch: 
    inputs:
      target_url:
        description: 'Target URL to scan'
        required: true
        default: 'https://staging.yourapp.com'

jobs:
  zap-baseline:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name:  Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target:  ${{ github.event.inputs.target_url || 'https://staging.yourapp.com' }}
          rules_file_name: '.zap/rules.tsv'  # Optional: custom rules
          fail_action: false  # Don't fail build; set to true once stable
          allow_issue_writing: true  # Creates GitHub issues for findings
          artifact_name: zap-baseline-report

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-baseline-report
          path: report_html.html
          retention-days: 90