name: OWASP ZAP Baseline Scan

on:
  workflow_call:
    inputs:
      target_url:
        description: 'Target URL to scan'
        required: true
        type: string
        default: 'https://staging.yourapp.com'
      rules_file_name:
        description: 'Optional ZAP rules file path (e.g., .zap/rules.tsv)'
        required: false
        type: string
        default: '.zap/rules.tsv'
      allow_issue_writing:
        description: 'Allow creating GitHub issues for findings'
        required: false
        type: boolean
        default: true

jobs:
  zap-baseline:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name:  Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target:  ${{ inputs.target_url || 'https://staging.yourapp.com' }}
          rules_file_name: ${{ inputs.rules_file_name }}  # Optional: custom rules
          fail_action: false  # Don't fail build; set to true once stable
          allow_issue_writing: ${{ inputs.allow_issue_writing }}  # Creates GitHub issues for findings
          artifact_name: zap-baseline-report

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-baseline-report
          path: report_html.html
          retention-days: 90